<?xml version="1.0" encoding="utf-8"?>
<Database Name="offLineBBHome" Class="offlineBbhomeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.100.242\myzjdw2008;Initial Catalog=offLineBBHome;User ID=sa" SettingsObjectName="ConsoleApplication2.Properties.Settings" SettingsPropertyName="offLineBBHomeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Ga_guidUserID" Member="Ga_guidUserIDs">
    <Type Name="Ga_guidUserID">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="guid" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ob_v_visitreport" Member="ob_v_visitreports">
    <Type Name="ob_v_visitreport">
      <Column Name="category" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="productid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="productName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>